import os,sys
os.system('clear')
os.system('sleep 3')
print("")
print ("Installing dependencies!!")
os.system('sleep 3')
os.system('pkg update -y')
os.system('pkg upgrade-y')
os.system('pkg install git -y')
os.system('pkg install wget -y')
os.system('pkg install curl -y')
os.system('pkg install openssl -y')
os.system('pkg install python2 -y')
os.system('pip2 install requests')
os.system('pip2 install mechanize')
os.system('pip2 install bs4')
os.system('pip2 install uncompyle6')
os.system('npm install -g bash-obfuscate')
